---
- name: Set local_fqdn fact (inventory_hostname)
  tags: setenv
  set_fact:
    local_fqdn: "{{ inventory_hostname }}"
  when: inventory_hostname != 'localhost'

- name: Set local_fqdn fact (ansible_fqdn)
  tags: setenv
  set_fact:
    local_fqdn: "{{ ansible_fqdn }}"
  when: inventory_hostname == 'localhost'

- name: Set class, product, env, and tld facts
  tags: setenv
  set_fact:
    local_class: "{{ local_fqdn.split('.')[0] }}"
    local_product: "{{ local_fqdn.split('.')[1] }}"
    local_env: "{{ local_fqdn.split('.')[2] }}"
    local_tld: "{{ local_fqdn.split('.')[3] }}"

- name: Set domain and search facts
  tags: setenv
  set_fact:
    local_domain: "{{ local_env }}.{{ local_tld }}"
    local_search: "{{ local_product }}.{{ local_env }}.{{ local_tld }}"
